app:
  id: uaa-service
apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://106.13.129.169:8080
  cacheDir: /app/war/apollo/temp/

spring:
  application:
    name: uaa-service
  # zipkin
  zipkin:
    base-url: http://localhost:9411

# 端口设置
server:
  port: 8081
  servlet:
    session:
      timeout: 600
# 集成Mybatis
mybatis:
  # Mybatis映射
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.javahly.uaaservice.entity


eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://49.233.192.8:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS



# 必须改成这种格式否则无法注册
server.servlet.context-path: /v1/uaa