spring:
  application:
    name: gateway-service
  cloud:
    # 网关配置
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # 权限认证路由
      - id: uaa-route
        uri: lb://uaa-service
        predicates:
        - Path=/uaa-service/**
        filters:
        - StripPrefix=1
        # 基本信息路由
      - id: basic-route
        uri: lb://basic-info-service
        predicates:
        - Path=/basic-service/**
        filters:
        - StripPrefix=1
        # 实训路由
      - id: training-route
        uri: lb://training-service
        predicates:
        - Path=/training-service/**
        filters:
        - StripPrefix=1
        # 请假服务路由
      - id: training-route
        uri: lb://ask-for-leave-service
        predicates:
        - Path=/leave-service/**
        filters:
        - StripPrefix=1

  # 链路追踪配置
  zipkin:
    base-url: http://localhost:9411

# 注册中心配置
eureka:
  client:
    registryFetchIntervalSeconds: 1
    service-url:
      defaultZone:  http://49.233.192.8:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# 网关服务端口
server:
  port: 8889

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/v1/uaa/oauth/current
    client:
    # 客户端Id ，与OAuth Provider 中的配置一一对应
      clientId: client-servic
      # 客户端密码，与OAuth Provider 中的配置一一对应
      clientSecret: 123456
      # 获取Token的节点
      accessTokenUri: http://localhost:8081/v1/uaa/oauth/token
      grant-type: client_credentials,password
      # 客户端的域
      scope: server