spring:
  application:
    name: gateway-service
  cloud:
    # 网关配置
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # 权限认证路由
      - id: uaa-route
        uri: lb://uaa-service
        predicates:
        - Path=/uaa-service/**
        filters:
        - StripPrefix=1
        # 基本信息路由
      - id: basic-route
        uri: lb://basic-info-service
        predicates:
        - Path=/basic-service/**
        filters:
        - StripPrefix=1
        # 实训路由
      - id: training-route
        uri: lb://training-service
        predicates:
        - Path=/training-service/**
        filters:
        - StripPrefix=1
        # 请假服务路由
      - id: leave-route
        uri: lb://ask-for-leave-service
        predicates:
        - Path=/leave-service/**
        filters:
        - StripPrefix=1
  redis:
    sentinel:
      master: mymaster
      nodes: 106.13.9.117:26379,123.56.219.53:26379,106.13.1.171:26379
    # Redis数据库索引，默认为0
    database: 0
    # Redis服务器地址
    #host: 106.13.9.117
    # Redis服务器连接端口
   #port: 16379
    # Redis密码，默认为空
    # Redis连接池最大连接数(负值表示没有限制
    jedis:
      pool:
        max-active: 10
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时时间
    timeout: 300000
    password: "!@#redis"
  # 链路追踪配置
  zipkin:
    base-url: http://localhost:9411

# 注册中心配置
eureka:
  client:
    registryFetchIntervalSeconds: 1
    service-url:
      defaultZone:  http://49.233.192.8:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# 网关服务端口
server:
  port: 8889
